# Generated by Django 5.0.3 on 2024-03-06 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.base')),
                ('title', models.CharField(max_length=255, verbose_name='Ф.И.О')),
                ('description', models.CharField(max_length=255, verbose_name='Кратное описание')),
                ('text', models.TextField(default='', verbose_name='Полное описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/event_courses/', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
            },
            bases=('main.base',),
        ),
    ]
