# Generated by Django 5.0.3 on 2024-03-06 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_eventcarousel_title_eventprogramm'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventProgramm',
            new_name='EventProgram',
        ),
    ]
