# Generated by Django 5.0.3 on 2024-03-06 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_eventprogramm_eventprogram'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventeatcarousel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='eventeatcarousel',
            name='text',
        ),
        migrations.AddField(
            model_name='event',
            name='eat',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Еда (меню)'),
        ),
    ]
