# Generated by Django 5.0.3 on 2024-03-06 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_eventeatcarousel_description_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventEatCarousel',
            new_name='EventEat',
        ),
        migrations.AlterModelOptions(
            name='eventeat',
            options={'verbose_name': 'Фото еды', 'verbose_name_plural': 'Фото еды'},
        ),
    ]
