# Generated by Django 5.0.3 on 2024-03-06 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_eventeatcarousel_eventeat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='сonditions',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Условия'),
        ),
    ]
