# Generated by Django 5.0.3 on 2024-03-11 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_aboutus'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='sale',
            field=models.BooleanField(blank=True, default=False, verbose_name='Акция'),
        ),
    ]
